/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Discipline = {
  _id: string;
  _type: "discipline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  displayOrder?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type VerticalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "vertical";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  disciplines?: Array<string>;
  metaLocation?: string;
  siteUrl?: string;
  vertical?: VerticalReference;
  displayOrder?: number;
  heroHeadline?: string;
  heroDescription?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  solutionHeadline?: string;
  solutionDescription?: string;
  solutionImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  resultHeadline?: string;
  resultDescription?: string;
  additionalImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Vertical = {
  _id: string;
  _type: "vertical";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  meta?: string;
  displayOrder?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Discipline
  | Slug
  | VerticalReference
  | SanityImageAssetReference
  | CaseStudy
  | SanityImageCrop
  | SanityImageHotspot
  | Vertical
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../rvnw-studios-site/src/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)] | order(displayOrder asc) {  _id,  title,  "slug": slug.current,  disciplines,  metaLocation,  siteUrl,  displayOrder,  "vertical": vertical->{"slug": slug.current, title},  heroHeadline,  heroDescription,  "heroImage": heroImage{  "url": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,  alt},  solutionHeadline,  solutionDescription,  "solutionImage": solutionImage{  "url": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,  alt},  resultHeadline,  resultDescription,  "additionalImages": additionalImages[]{  "url": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,  alt}}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  disciplines: Array<string> | null;
  metaLocation: string | null;
  siteUrl: string | null;
  displayOrder: number | null;
  vertical: {
    slug: string | null;
    title: string | null;
  } | null;
  heroHeadline: string | null;
  heroDescription: string | null;
  heroImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
    alt: string | null;
  } | null;
  solutionHeadline: string | null;
  solutionDescription: string | null;
  solutionImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
    alt: string | null;
  } | null;
  resultHeadline: string | null;
  resultDescription: string | null;
  additionalImages: Array<{
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
    alt: string | null;
  }> | null;
}>;

// Source: ../rvnw-studios-site/src/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  disciplines,  metaLocation,  siteUrl,  displayOrder,  "vertical": vertical->{"slug": slug.current, title},  heroHeadline,  heroDescription,  "heroImage": heroImage{  "url": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,  alt},  solutionHeadline,  solutionDescription,  "solutionImage": solutionImage{  "url": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,  alt},  resultHeadline,  resultDescription,  "additionalImages": additionalImages[]{  "url": asset->url,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,  alt}}
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  disciplines: Array<string> | null;
  metaLocation: string | null;
  siteUrl: string | null;
  displayOrder: number | null;
  vertical: {
    slug: string | null;
    title: string | null;
  } | null;
  heroHeadline: string | null;
  heroDescription: string | null;
  heroImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
    alt: string | null;
  } | null;
  solutionHeadline: string | null;
  solutionDescription: string | null;
  solutionImage: {
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
    alt: string | null;
  } | null;
  resultHeadline: string | null;
  resultDescription: string | null;
  additionalImages: Array<{
    url: string | null;
    width: number | null;
    height: number | null;
    lqip: string | null;
    alt: string | null;
  }> | null;
} | null;

// Source: ../rvnw-studios-site/src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "caseStudy" && defined(slug.current)] | order(displayOrder asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  disciplines,\n  metaLocation,\n  siteUrl,\n  displayOrder,\n  "vertical": vertical->{"slug": slug.current, title},\n  heroHeadline,\n  heroDescription,\n  "heroImage": heroImage{\n  "url": asset->url,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n  alt\n},\n  solutionHeadline,\n  solutionDescription,\n  "solutionImage": solutionImage{\n  "url": asset->url,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n  alt\n},\n  resultHeadline,\n  resultDescription,\n  "additionalImages": additionalImages[]{\n  "url": asset->url,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n  alt\n}\n}\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && slug.current == $slug][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  disciplines,\n  metaLocation,\n  siteUrl,\n  displayOrder,\n  "vertical": vertical->{"slug": slug.current, title},\n  heroHeadline,\n  heroDescription,\n  "heroImage": heroImage{\n  "url": asset->url,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n  alt\n},\n  solutionHeadline,\n  solutionDescription,\n  "solutionImage": solutionImage{\n  "url": asset->url,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n  alt\n},\n  resultHeadline,\n  resultDescription,\n  "additionalImages": additionalImages[]{\n  "url": asset->url,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n  alt\n}\n}\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "caseStudy" && defined(slug.current)].slug.current\n': PROJECT_SLUGS_QUERY_RESULT;
  }
}
